apiVersion: v1
kind: Service
metadata:
  name: devops-03-pipeline-aws-service
  namespace: default
  labels:
    app: devops-03-pipeline-aws
spec:
  selector:
    app: devops-03-pipeline-aws
  ports:
    - port: 8080        # Cluster içinden erişim için Service portu
      targetPort: 8080  # Pod içindeki container portu
  type: LoadBalancer      
#  type: ClusterIP       # Dışarıya açılmaz, port-forward ile kullanacağız
